[package]
name = "synth_wasm"
version = "0.1.0"
authors = ["Kasper Nielsen <kasper0406@gmail.com>"]
edition = "2018"

[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.17"
console_error_panic_hook = "0.1.6"
js-sys = "0.3.47"

[lib]
crate-type = ["cdylib"]
