[package]
name = "synth"
version = "0.1.0"
authors = ["Kasper Nielsen <kasper0406@gmail.com>"]
edition = "2018"

[dependencies]
portaudio = "0.7.0"
gnuplot = "0.0.37"
num = "0.2.0"
lazy_static = "1.4.0"

[[bin]]
name = "backend"
path = "main.rs"
